### PR TITLE
Removed question mark that did not allow to build the solution

### PR DESCRIPTION
**Pull request by Totemika**
I'm not sure if this is a typo or not :question:

### CODE REVIEW

**Comment by dachibox** [comment]
This is a new feature on roslyn. You can easly check nullable properties/objects. f the error continue, we can change on a normal sentence.

if (wv != null) wv.NavigateToString((string) e.NewValue);

**Comment by Totemika** [comment]
I don't know... I'm afraid of adding that roslyn thing to my VS2013. I could try to get VS2015. We should add a section in the README.md specifying the exact tools needed for developing for this project. What do you think?

What do you think about moving this Wiki page to a section in the README.md? 
https://github.com/GeekyTheory/GeekyBlogs/wiki

**Comment by Totemika** [comment]
I'm going to add you to Skype too so you can easily tell me what you would like me to do

**Comment by Mouse-** [comment]
my Skype account is:mouse_@outlook.com
you can add me by this email.
 
Date: Thu, 12 Mar 2015 01:38:07 -0700

**Pull request closed without merging**
